// Bundled sample tracks so GPXKit can be tried without the user's own GPX
// file (mirrors ParquetKit's "query a sample dataset" pattern). Generated by
// scripts/generate_demo_gpx.py — a plausible-looking loop trail, not a
// recording of a real place.

export const DEMO_TRACK_URL = "/demo/sample-hike.gpx";
export const DEMO_TRACK_PART1_URL = "/demo/sample-hike-part1.gpx";
export const DEMO_TRACK_PART2_URL = "/demo/sample-hike-part2.gpx";

export async function fetchAsFile(url: string, fileName: string): Promise<File> {
  const response = await fetch(url);
  if (!response.ok) {
    throw new Error(`Failed to load sample track: ${url}`);
  }
  const text = await response.text();
  return new File([text], fileName, { type: "application/gpx+xml" });
}
